
UPSTOX_ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJrZXlfaWQiOiJza192MS4wIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIxMDc1NzYiLCJqdGkiOiI2YTIyOWU4OGFlNDkxNjdmOWQ1OTExYWEiLCJpc011bHRpQ2xpZW50IjpmYWxzZSwiaXNQbHVzUGxhbiI6ZmFsc2UsImlzRXh0ZW5kZWQiOnRydWUsImlhdCI6MTc4MDY1MzcwNCwiaXNzIjoidWRhcGktZ2F0ZXdheS1zZXJ2aWNlIiwiZXhwIjoxODEyMjMyODAwfQ.lu0yy15XiBQKQNtas8VJTkH-mp6_L_QR8PlUJgqqeuk"
GITHUB_REPO = "rkovath-netizen/Quant-Setup_back_test" 
GMAIL_USER = "ramkov199@gmail.com"
GMAIL_APP_PASSWORD = "lvgw cohg eucb cedw"
GITHUB_BRANCH = "main"
